# Generated by Django 4.0.6 on 2022-07-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myImageFolder')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
